# Generated by Django 5.1.6 on 2025-08-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='vartion_value',
            new_name='variation_value',
        ),
    ]
