# Generated by Django 5.1.6 on 2025-08-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_vartion_value_variation_variation_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Variation_category',
            new_name='variation_category',
        ),
    ]
