# Generated by Django 5.1.6 on 2025-08-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_variation_category_variation_variation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/product_variations'),
        ),
    ]
